### ISSUE TITLE
list/player - vracet team_id

### ISSUE THREAD

**Issue by vosecek** [YoSarin/cald-database-backend#10]
Šlo by prosím přidat team_id do odpovědi na list/player?

**Comment by YoSarin** [comment]
Budu muset trochu předělat ten extended flag - používáš to někde?

**Comment by vosecek** [comment]
Pouzivam docela dost a nerad bych to predelaval :)

**Comment by vosecek** [comment]
Uz neni treba resit, obejdu to stahovanim vsech hracu v tymech, 150 kb holt kazdy prezije pri spusteni aplikace.
