### ISSUE TITLE
Chyba 500 u player/id/history

### ISSUE THREAD

**Issue by vosecek** [YoSarin/cald-database-backend#23]
Asi 20 hracu konci s chybou serveru 500 pri proverovani jejich historie. Priklady:
http://api.evidence.cald.cz/player/42/history?token=d6086d5597a59dcf3ac9977356b49038dbe5792f58fb59af3e1f02f502e0bac1

dalsi ID:
104
317
325
568
595
612
...
1548
1674

Zároveň jsem si všiml že třeba Zuzana Bělinová je v Oddílu 3SB vypisovaná, i když je registrovaná v Terrible Monkeys. V 3SB někdy dávno byla, ale přestup byl dávno udělaný, ale ne s definicí k jaké sezoně.

**Comment by vosecek** [comment]
Problém s nejvyšší prioritou

**Comment by YoSarin** [comment]
Vypadá to jako vyřešený...
