### ISSUE TITLE
Oznaceni soupisky jako Finální

### ISSUE THREAD

**Issue by vosecek** [YoSarin/cald-database-backend#24]
Možnost označit soupisku jako Finální

**Comment by vosecek** [comment]
tokan by mel byt od administratora, nebo od spravce turnaje

**Comment by YoSarin** [comment]
viz https://github.com/YoSarin/cald-database-backend/blob/master/api.md#post-rosterroster_idfinalize a https://github.com/YoSarin/cald-database-backend/blob/master/api.md#post-rosterroster_idopen. Zkontroluj a kdyžtak reopen.
