### ISSUE TITLE
Nové vlastnosti Hráče (GDPR) - Nejvyšší priorita

### ISSUE THREAD

**Issue by vosecek** [YoSarin/cald-database-backend#26]
- národnost (editovatelný číselník by byl optimální, ale je to dost práce, stačit bude myslím textové pole kam frontend evidence bude posílat pevně dané hodnoty)
- trvalý pobyt
- adresa pobytu (pokud národnost nebude Česká)
- udělen souhlas se zpracováním údajů, boolean

**Comment by YoSarin** [comment]
je to na cald.yosarin.net, zkontroluj to a případně zavři/dookomentuj.

S Kačerem se pak domluv na deployi (bude to chtít nějaký úpravy v DB, je tam na to připravenej ne-uplně-hezkej-alefunkční migrační skriptík) (viz https://github.com/YoSarin/cald-database-backend/blob/master/data/README.md )

Popis novejch api je v https://github.com/YoSarin/cald-database-backend/blob/master/api.md (přidávání adresy hráčům, gdpr consent a národnost), api pro přidání novejch národností je popsaný v admin.md
