### ISSUE TITLE
Duplikace výsledků na list/player_at_team

### ISSUE THREAD

**Issue by vosecek** [YoSarin/cald-database-backend#28]
request: http://cald.yosarin.net/list/player_at_team?filter%5Bteam_id%5D=49&extend=1&token=a2a9f5e49a9d98932c7b6618990a14f4c52fc8d376c6720aeb8e13d9340a4aef

vraci se napriklad trikrat ID 1192, Maskova Michaela.

**Comment by YoSarin** [comment]
vypadá to, že na cald.yosarin.net je to OK, zavírám
