### ISSUE TITLE
team/id/user/id

### ISSUE THREAD

**Issue by vosecek** [YoSarin/cald-database-backend#3]
Admin nemůže přiřazovat uživatele k týmu, error 403.

Navíc pokud nemám zapnutý CORS, vrací se: No 'Access-Control-Allow-Origin' header is present on the requested resource

Teprv s CORS v prohlížeči alespoň získám chybovou hlášku, že nemám oprávnění přiřadit uživatele.

**Comment by YoSarin** [comment]
Zvláštní Access-Control-Allow-Origin:* by se měl v middleware nastavovat dycky... Co znamená "nemám zapnutý CORS"? Nějakou hlavičku neposíláš?

Jinak ta 403 už by měla bejt cajk - nějak se mi během developmentu ty admin práva potratily...

**Comment by vosecek** [comment]
Plugin do Chromu přidává ke každému requestu:
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Authorization, Auth, Token, Access-Token, Access_Token, AccessToken, Code, Authentication
