### ISSUE TITLE
post/team/:id

### ISSUE THREAD

**Issue by vosecek** [YoSarin/cald-database-backend#4]
Admin nemůže upravovat detail týmu, error 403.

**Comment by YoSarin** [comment]
fixwd by #1416ee0

**Comment by vosecek** [comment]
Pri zmene nazvu tymu ci zadani datumu zalozeni se vraci chyba 403 - Privilege already exists

**Comment by vosecek** [comment]
Tak update - data se upraví, ale vrací se popsaná chyba namísto potvrzený aktualizace dat.
