### ISSUE TITLE
Narodnost - iso kody s nazvy

### ISSUE THREAD

**Issue by vosecek** [YoSarin/cald-database-backend#42]
Data pro databazi: https://ulozto.cz/tam/f9bd7600-59fa-4146-a24d-fe2898f6a009

k poradovemu ID a nazvu obcanstvi jeste potrebujeme kod, protoze Hnilicka chodi na party s Bendlem a misto dobre naplanovaneho systemu chlasta a pak se to trikrat predelava.

**Comment by YoSarin** [comment]
krásný číslo issue :D

**Comment by vosecek** [comment]
Nefunguje PUT na nastaveni iso_code, kdyby se tam neco menilo, ani POST, kdyby se neco vytvarelo. Ale to je asi jedno, protoze nove staty moc nevznikaji a krome toho to setjne budem asi resit synchronizaci s daty od NSA.

**Comment by YoSarin** [comment]
Dobrej point, udělám na to nový issues
