### ISSUE TITLE
list/tournament - filtrování podle parametru date nefunguje

### ISSUE THREAD

**Issue by vosecek** [YoSarin/cald-database-backend#5]
při date[>]:2010-01-01 se nevrátí nic
při date[>]:přesný datum a čas nějakýho turnaje se vrátí ten turnaj
při date[>=]:2010-01-01 se vrátí úplně všechny turnaje

Potřebuju to na výpis turnajů co teprv budou, což zatím ošetřím filtrováním na straně klienta, takže to nijak nehoří.

**Comment by YoSarin** [comment]
Je bohužel potřeba udělat encode dvakrát (alespoň při curl requestu):
```filter[date%255B>%255D]=2016-08-01```
>= nefunguje nevím proč, jestli ho nutně nepotřebuješ, tak bych to nechal být...
