### ISSUE TITLE
POST/DELETE roster/{roster_id}/player/{player_id}

### ISSUE THREAD

**Issue by vosecek** [YoSarin/cald-database-backend#9]
POST i DELETE roster/854/player/1202

Chyba 500 Database went off

**Comment by vosecek** [comment]
Stale nefunguje, ani jedna metoda. Ted se vraci chyba 403, not authorized.

**Comment by YoSarin** [comment]
Sorry, jsem to zkoušel jen s adminem... :( Fixnuto i tohle...
